[defaults]
shell = "bash"

[commands.just-fmt]
command = "just --fmt --unstable"
tags = ["format"]

[commands.nixfmt]
command = "fd -e nix -x nixfmt"
tags = ["fd", "format"]

[commands.standard-clj-fmt]
command = "standard-clj fix"
tags = ["format"]

[commands.taplo-fmt]
command = "fd -e toml -x taplo fmt"
tags = ["fd", "format"]

[plots.histogram]
file = "plot-histogram.png"
type = "histogram"

[plots.whisker]
file = "plot-whisker.png"
type = "whisker"
